# Generated by Django 4.1.7 on 2023-05-05 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_followrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='to_follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
