# Generated by Django 4.1.7 on 2023-05-19 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_followrequest_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
