# Generated by Django 4.2.1 on 2023-05-27 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_user_is_active_accountconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 28, 18, 19, 38, 667748, tzinfo=datetime.timezone.utc)),
        ),
    ]
