# Generated by Django 4.2.1 on 2023-07-20 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_accountconfirmation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 9, 1, 46, 674282, tzinfo=datetime.timezone.utc)),
        ),
    ]
