# Generated by Django 4.2.1 on 2023-07-20 11:40

import datetime
from django.db import migrations, models
import encrypted_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_accountconfirmation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=encrypted_field.fields.EncryptedField(blank=True, default='Adresa nije uneta', null=True),
        ),
        migrations.AlterField(
            model_name='accountconfirmation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 21, 11, 40, 3, 681392, tzinfo=datetime.timezone.utc)),
        ),
    ]
